name: Static site CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-html:
    name: Lint HTML and serve site
    runs-on: windows-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: start local web browser
        run: |
           python -m http server 8080 &
        shell: bash


      - name: Serve site and smoke test
        run: |
          start http://localhost:8080/index.html
        shell: cmd

     
